# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "CCWebArch"
client_id = "fc10140194da0eb4be42235c66b881d4"
application_url = "https://cornell-spas-adjusted-message.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_discounts"

[auth]
redirect_urls = [
  "https://cornell-spas-adjusted-message.trycloudflare.com/auth/callback",
  "https://cornell-spas-adjusted-message.trycloudflare.com/auth/shopify/callback",
  "https://cornell-spas-adjusted-message.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ccwebarch.myshopify.com"
